#!/bin/bash
#Script resizes images to 50% from original sizes. Uses imagemagic

input="$1";
out_dir="resized66p/";


#&& 
#if [ ! -z ${imput} ] 
if [ ! -s "$input" ]; 
then 
    echo "First argument '$input' must be a input image file, but it is not "
    echo "Lets process all current directory"
    time for i in *.*g; 
        do echo -e "\n$i: ";
        eval "$0 \"${i}\"";
    done;
    echo "";
    exit;
fi;

echo -ne "Processing \"${input}\" ";
mkdir -p "$out_dir";

echo -ne ".";

#convert "${input}" -verbose -antialias -blur 0x1 -liquid-rescale "66.666%x66.666%" -sharpen 0x2 -interlace plane -quality 100 "${output}"; 
/usr/bin/time --format=%e convert "${input}" -verbose -antialias  -adaptive-resize "200%x200%" -resize "50%x50%" -liquid-rescale "66.666%x66.666%" -interlace plane -quality 100 "${out_dir}${input%.*}.png"; 
#time convert "${input}" -verbose -antialias -blur 0x1 -liquid-rescale "66.666%x66.666%" -sharpen 0x2 -interlace plane -quality 100 "${out_dir}${input%.*}-blur.png"; 

