#!/bin/bash
. /home/i/.profile;
export $(dbus-launch)
DISPLAY=":0"

camera_dir="/home/i/downloads/cam/";
screen_dir="$HOME/screenshots/";
target_dir="/home/i/dobro/online/$(cat /etc/hostname)/cam/";


#echo "" > commands.bash;

sleeptime="0.15";
function execute_comm {
    sleeptime="0.1";
    echo -e "\n\nExecute '$1'";
    sleep $sleeptime;
    #echo "$1" >> commands.bash;
    sleep $sleeptime;
    echo "";
    eval "$1";
}


execute_comm " ";

#
#Get image from all of web-cam
for i in `ls /dev/vid*`; 
    do echo -n ""; sleep 0.2;
    mkdir -pv "${camera_dir}"
    cd "${camera_dir}";
    last_image_fname_png="$(basename "${i}").png";
    last_image_fname_jpg="$(basename "${i}").jpg";
    execute_comm "ffmpeg -hide_banner -y -s 3840x2160 -f video4linux2 -i ${i} -vframes 1 -vf pp=ac/al\|fullyrange/dr/ha/va,unsharp -q:v 0 \"${camera_dir}/${last_image_fname_png}\""
    execute_comm "convert \"${last_image_fname_png}\" -verbose -antialias -colorspace YCbCr -auto-level -interlace plane -background white -quality 64 -sampling-factor 2x2 -flatten -define jpeg:dct-method=float \"${camera_dir}/${last_image_fname_jpg}\""
    execute_comm "rm -vf \"${camera_dir}/${last_image_fname_png}\""
    mkdir -pv "${target_dir}";
    cd "${target_dir}";
    target_fname="$(date "+%F-%H-%M-%S")-${last_image_fname_jpg}";
    execute_comm "mv \"${camera_dir}/${last_image_fname_jpg}\" \"${target_dir}/${target_fname}\"";
done;

export DISPLAY=$(w $(id -un) | awk 'NF > 7 && $2 ~ /tty[0-9]+/ {print $3; exit}')
echo "DISPLAY=$DISPLAY";
export DISPLAY=$(w $(id -un) | awk 'NF > 7 && $2 ~ /tty[0-9]+/ {print $3; exit}')
echo "DISPLAY=$DISPLAY";
DISPLAY=":0.0"
export $DISPLAY

execute_comm "xdpyinfo | grep 'dimensions:'";
CUR_RESOLUTION=`xdpyinfo | grep 'dimensions:' | awk '{print $2}'`;
echo "CUR_RESOLUTION=${CUR_RESOLUTION}";
CUR_RESOLUTION=`xrandr -q|sed -n 's/.*current[ ]\([0-9]*\) x \([0-9]*\),.*/\1x\2/p'`;
echo "CUR_RESOLUTION=${CUR_RESOLUTION}";
#xrandr --current | grep 'current'
mkdir -pv "${screen_dir}"
cd "${screen_dir}";
target_fname_png="$(date "+%F-%H-%M-%S")-screen.png";
target_fname_jpg="$(date "+%F-%H-%M-%S")-screen.jpg";
echo $target_fname_jpg; 
execute_comm "ffmpeg -y -hide_banner -s ${CUR_RESOLUTION} -f x11grab -i :0.0  -vframes 1 \"${screen_dir}/${target_fname_png}\" "
execute_comm "convert \"${screen_dir}/${target_fname_png}\" -verbose -adaptive-resize 50%x50% -antialias -colorspace YCbCr -auto-level -interlace plane -background white -quality 33 -sampling-factor 2x2 -flatten -define jpeg:dct-method=float \"${screen_dir}/${target_fname_jpg}\""
execute_comm "rm -vf \"${screen_dir}/${target_fname_png}\""
mkdir -pv "${target_dir}";
cd "${target_dir}";
execute_comm "mv -v \"${screen_dir}/${target_fname_jpg}\" \"${target_dir}/${target_fname_jpg}\"";

