#!/bin/bash
#Script converts DNG to jpg

#echo "" > commands.bash;
# input="$1";
# if [ ! -s "$input" ];
# then
#     echo "First argument '$input' must be a input image file, but it is not "
#     echo "Lets process all current directory"
#     for i in *.*;
#         do echo -e "\n$i: ";
#         eval "$0 \"${i}\"";
#     done;
#     echo "";
#     exit;
# fi;
#
# sleeptime="0.15";
# function execute_comm {
#     sleeptime="0.1";
#     echo -e "\n\nExecute '$1'";
#     sleep $sleeptime;
#     echo "$1" >> commands.bash;
#     sleep $sleeptime;
#     echo "";
#     eval "$1";
# }

#Let's set CPU threads count
threads=$(grep -c ^processor /proc/cpuinfo);
#echo $threads;
threads=$((threads / 2 - 1));
echo $threads;
sleep 0.1;

MAX_JOBS=$threads;
#MAX_JOBS=1;
echo "$MAX_JOBS" > MAX_JOBS_VALUE;
NEWDIRPNG="PNGed";
NEWDIRJPEG="JPEGed";
NEWDIRJSON="JSON-EXIF";
TEMPDIR="TEMPDIR";
COMPUTEDDIR="COMPUTED";

mkdir -pv "$TEMPDIR" "$COMPUTEDDIR" "$NEWDIRPNG" "$NEWDIRJPEG" "$NEWDIRJSON";

time ( for f in *.dng; do ( echo "   $f"; \

dcraw -v -q 1 -f -w -6 -p embed -T "${f}";
mv -v "${f%.*}.tiff" "${TEMPDIR}/";

#Try to export exif-data from DNG
exiftool -all:all -extractEmbedded -json -b "${f}"  > "${NEWDIRJSON}/${f%.*}.json";
#Try to export exif-data from jpeg with same name
#exiftool -extractEmbedded -json "${f%.*}.jpg" > "${NEWDIRJSON}/${f%.*}-j.json";

sed -i '/Orientation/d; /FileName/d; /SourceFile/d; /FileType/d; /FileTypeExtension/d; /MIMEType/d; /MajorBrand/d; /Directory/d; /ExifToolVersion/d; /FileSize/d; /FileModifyDate/d; /MediaDataSize/d; /MediaDataOffset/d; ' "${NEWDIRJSON}/${f%.*}.json";

#exiftool -overwrite_original -j+="${NEWDIRJSON}/${f%.*}.json" "${TEMPDIR}/${f%.*}.tiff";

/usr/bin/time --format=%e magick "${TEMPDIR}/${f%.*}.tiff" \
-auto-orient \
-depth 16 \
-modulate 100%,199%,-100% \
-colorspace sRGB \
-define jpeg:dct-method=float -interlace JPEG \
-quality 100 -sampling-factor 4:4:4 \
-define png:compression-level=9 \
+repage \
"${NEWDIRPNG}/${f%.*}.png";

/usr/bin/time --format=%e magick "${TEMPDIR}/${f%.*}.tiff" \
-auto-orient \
-colorspace sRGB \
-modulate 100%,199%,-100% \
-gamma 1.4 \
-define jpeg:dct-method=float -interlace JPEG \
-quality 100 -sampling-factor 4:4:4 \
-define png:compression-level=9 \
+repage \
"${NEWDIRJPEG}/${f%.*}.jpg";

#jpegtran -copy none -progressive -optimize -arithmetic -outfile "${NEWDIRJPEG}/${f%.*}.jpeg" "${NEWDIRJPEG}/${f%.*}.jpg";

#Import exif to new file
exiftool -overwrite_original -j+="${NEWDIRJSON}/${f%.*}.json" "${NEWDIRPNG}/${f%.*}.png";

exiftool -overwrite_original -j+="${NEWDIRJSON}/${f%.*}.json" "${NEWDIRJPEG}/${f%.*}.jpg";

mv -v "$f" "$COMPUTEDDIR/";
rm -v "${TEMPDIR}/${f%.*}.tiff";
) &
MAX_JOBS=$(cat MAX_JOBS_VALUE);
echo "Current jobs: $( jobs -r -p | wc -l ) MAX_JOBS: $MAX_JOBS ";
if [[ $(jobs -r -p | wc -l) -ge $(( $MAX_JOBS - 0 )) ]]; then wait -n; fi;
sleep 1;
done; wait;
mv -v  "$COMPUTEDDIR"/* ./;
rmdir --verbose "$TEMPDIR";
rmdir --verbose "$COMPUTEDDIR";
rm -v MAX_JOBS_VALUE;
echo "All jobs done"; );
sleep 0.3;
find . -size 0 -type f -exec rm -v '{}' \;
sleep 0.3;
find . -empty -type d -exec rmdir -v '{}' \;
sleep 0.3;
find . -empty -type d -exec rmdir -v '{}' \;
sleep 0.3;
