#!/bin/bash
#Script delete empty dirs and files
echo "Script delete empty dirs and files"
sleep 0.1;
find . -empty -type f -exec rm -v '{}' \;  
sleep 0.1;
find . -empty -type d -exec rmdir -v '{}' \;
sleep 0.1;
find . -empty -type d -exec rmdir -v '{}' \;
sleep 0.1;
find . -name "Thumbs.db:encryptable" -exec rm -v '{}' \; 
sleep 0.1;
find . -name "Thumbs.db" -exec rm -v '{}' \;


