#!/bin/bash
find . -type f -print0 | xargs -0n 1 bash -c 'fdirname=$(dirname "$0"); f=$(dirname "$0")/$(basename "$0"); n=$(basename "$0"); fextension="${n##*.}"; n="$n"; n="$fextension"/$(dirname "$0")/"$n"; if [ "$fextension" != "mv" ]; then mkdir -p "$(dirname "$n")"; mv --verbose --no-clobber --no-target-directory "$f" "$n"; echo mv -v \"$n\" \"$f\" >>anti_divide_by_ext.mv; else echo " -- skipping \"$f\""; fi; chmod +x anti_divide_by_ext.mv; '

