#!/bin/bash

log_file_path="/home/i/bin/logs/list_recursive.log";
all_file_path="/home/i/bin/logs/list_recursive_all_files.txt";
stat_file_path="/home/i/bin/logs/list_recursive_stat_files.txt";
sorted_file_path="/home/i/bin/logs/list_recursive_all_files_sorted.txt";
mkdir -pv "$(dirname "${log_file_path}")"
mkdir -pv "$(dirname "${all_file_path}")"
echo "" > "${all_file_path}";
echo "" > "${log_file_path}";

function list_recursive_here () {
    #function show find directories in current directories and recursively run itself
    #eval CUR_DIR="$1";
    CUR_DIR="$1";
    CUR_DIR=$(echo "${CUR_DIR}" | base64 --decode --ignore-garbage);
    BASE_DIR="$2";
    BASE_DIR=$(echo "${BASE_DIR}" | base64 --decode --ignore-garbage);
    #echo "${CUR_DIR} `date +%Y-%m-%d-%H-%M-%S`:" 
    echo cd "${CUR_DIR}";
    cd "${CUR_DIR}";
    FULL_DIR=$(realpath --relative-to="${BASE_DIR}" "`pwd`");
    echo -e "\n${FULL_DIR}" | tee --append "${all_file_path}" | tee --append "${stat_file_path}"
    stat --printf="%n\t%s\n" *  | tee --append "${stat_file_path}"
    #Scan current directory
    #find . -maxdepth 1 -type f -printf "%p\t%s\n" | tee --append "${all_file_path}"
    find -maxdepth 1 -type f -printf "${BASE_DIR}%p\t%s\n" | tee --append "${all_file_path}"
    
    #ls --color=always;
    #lets find directories in current directory
    find . -maxdepth 1 -type d -print0 | while IFS= read -r -d '' file; do
        # ...
        if [ "${file}" != "." ] && [ "${file}" != ".." ];
        then
            #echo "${file}";
            #IFS='"';
            NEXT_DIRNAME=$(basename "${file}");
            echo -n "DIRNAME=${NEXT_DIRNAME}=";
            NEXT_DIRNAME=$(echo "${NEXT_DIRNAME}" | base64 --wrap=0);
            BASE_DIR=$(echo "${BASE_DIR}" | base64 --wrap=0);
            #echo "${DIRNAME} ";
            list_recursive_here "${NEXT_DIRNAME}" "${BASE_DIR}";
        fi
    done;
    #cd ..;
}

CURRENT_DIR=`pwd`;
list_recursive_here "`echo "." | base64 --wrap=0`" "`echo "${CURRENT_DIR}" | base64 --wrap=0`";

#echo "121223412343" | base64 --wrap=0
#echo "MTIxMjIzNDEyMzQzCg==" | base64 --decode --ignore-garbage

cat "${all_file_path}" | sort > "${sorted_file_path}"
