#!/bin/bash

#Файл, позволяющий всё отменить
echo "#!/bin/bash" >>anti.mv
echo `date` >>anti.mv

for d in *.*; do echo -n "";

#Длина строки имени файла равна:
filenameleng=${#d}

#В нижний регистр переводим
newfname=`echo $d | tr 'A-Z' 'a-z'`

#Если в имени файла менее X символов - не обрабатываем его
if (("$filenameleng" >= "15"))
then
	#echo "#$d lenght:[$filenameleng] - приемлемое имя файла";
	new_d=${d:0:10};
	mkdir -p "$new_d";
	#Создаём жёсткую ссылку
	#ln "$d" "$new_d/$newfname";
	#Переносим файл в новое место и показываем команду для обратного переноса
	echo mv \""$new_d/$newfname"\" \""$d"\";
	echo mv \""$new_d/$newfname"\" \""$d"\" >>anti.mv;
	mv "$d" "$new_d/$newfname";
else
      echo "$d lenght:[$filenameleng] - слишком короткое имя файла";
fi

done;

