#!/bin/bash
sleep 0.5;
preffix=$1; 

find . -maxdepth 1 -type f -print0 | xargs -0n 1 bash -c 'preffix="'$preffix'"; f=$(dirname "$0")/$(basename "$0"); n=$(basename "$0"); n="$preffix$n"; n=$(dirname "$0")/$n; if [ "$f" != "$n" ]; then mv --verbose --no-clobber --no-target-directory "$f" "$n"; echo mv -v \"$n\" \"$f\" >>anti_preffix.mv; else echo " -- skipping \"$f\"" >/dev/null; fi; chmod +x anti_preffix.mv; '
#find . -maxdepth 1 -type f  -print0 | xargs -0n 1 bash -c 'preffix="'$preffix'"; echo $preffix; '
