#!/bin/bash
sleep 0.5;
#preffix=$1; 

sleep 1; find . -maxdepth 2 -type f -print0 | xargs -0n 1 bash -c 'f=$(dirname "$0")/$(basename "$0"); n=$(dirname "$0")/$(basename "$0"|perl -npe "s/^[. ]+//|s/\#/_/gi|s/\,/_/gi|s/\+/-/gi|s/\%/_/gi|s/\&/_/gi|s/\{/_/gi|s/\}/_/gi|s/\</_/gi|s/\>/_/gi|s/\*/_/gi|s/\?/_/gi|s/\$/_/gi|s/\!/_/gi|s/\"/_/gi|s/\s+/_/gi|s/Screenrecorder\-//gi|s/IMG_//gi|s/_HHT//gi|s/_HDR//gi|s/VID_//gi|s/PANO_//gi|s/Screenshot_//gi|s/\(/_/gi|s/\)/_/gi|s/\:/-/gi|s/\@/_/gi|s/\.jpeg/\.jpg/gi|s/___//gi|y/A-Z/a-z/"); if [ "$f" != "$n" ]; then mv --verbose --no-clobber --no-target-directory "$f" "$n"; echo mv --verbose \"$n\" \"$f\" >>antisanitize_filenames.mv; else echo " -- skipping \"$f\"" >/dev/null; fi; chmod +x antisanitize_filenames.mv; '

