#!/bin/bash 
#Скрипт задаёт дату из имени файла
#Файлы должны называться yyyy-mm-dd-hh-mm-ss

#set date from file name to its creation date
#Work with filenames like "2019-06-08-09-22-03--1118ms-1.jpg"
#convert it to "YYYY-MM-DD HH:mm:ss" format

#for i in *.*; do echo $i; filedate="${i:0:4}-${i:5:2}-${i:8:2} ${i:11:2}:${i:14:2}:${i:17:2}"; echo "date = ${filedate}"; touch -a -m --date="${filedate}" "${i}"; done;

for i in *.*; do echo -e "\n$i"; 
filedate="${i:0:4}-${i:5:2}-${i:8:2} ${i:11:2}:${i:14:2}:${i:17:2}"; 
datesecs=$(date +%s --date="${filedate}")
#2019-08-11-14-10-31--482827ms-11
dateoffsetsecs=${i:21:9}
#get only digits from variable
dateoffsetsecs=$(echo ${dateoffsetsecs} | grep -o -E '[0-9]+' | head -1 | sed -e 's/^0\+//')
echo -n "dateoffsetsecs = ${dateoffsetsecs}";
dateoffsetsecs=$((dateoffsetsecs / 1000));
#dateoffsetsecs=`calc "${dateoffsetsecs} / 1000"`;
echo -n "dateoffsetsecs = ${dateoffsetsecs}";
datesecs=$((datesecs + dateoffsetsecs));
echo -n "datesecs = ${datesecs}";
filedate=$(date '+%F %H:%M:%S' --date="@${datesecs}")
echo -n "date = ${filedate}";
if [ "${datesecs}" -gt "31536000" ]
then touch -a -m --date="${filedate}" "${i}";
else echo -n " -- skipping \"${i}\" cause its too old"; 
fi; 

done;
