#!/bin/bash
#Script copying everything from one dir to another in file size order (from smallest files to bigger
#Using rsync

FROM="${1}/"; 
TO="${2}/"; 

if [ -z "$1" ]
    then
    FROM=$(pwd);
    echo "First argument is a \"from\"-directory and it is empty string"
    echo "from-directory set to current dir (${FROM})";
fi

if [ -z "$2" ]
    then
    TO=$(pwd); TO="${TO}/copy-by-size";
    echo "Second argument is a \"to\"-directory and it is empty string"
    echo "to-directory set to current dir (${TO})";
fi

MIN_SIZE=0; 
for MAX_SIZE in 0b 1b 300b 1k 10k 100k 300k 1m 3m 10m 30m 100m 300m 1g 3g 10g 30g 100g 300g 1000g 999999g; 
do echo -e "\n\nMIN_SIZE=${MIN_SIZE} MAX_SIZE=${MAX_SIZE}\n\n"; 
    mkdir -pv "${TO}"; 
    sleep 0.1; 
    rsync --min-size=${MIN_SIZE} --max-size=${MAX_SIZE} --info=progress2 --progress --recursive --times --human-readable --verbose --exclude=".git" "${FROM}/" "${TO}/"; MIN_SIZE=$MAX_SIZE; 
done;
