#!/bin/bash
#Script copying everything from one dir to another in file size order (from smallest files to bigger
#Using rsync

FROM="${1}/"; 
TO="${2}/"; 
EXCLUDE=" --exclude=\".git\" ";
COPY_TO_SAME_DIR=0; #flag variable
COPY_BY_SIZE_DIR="copy-by-size";

function execute_comm {
    sleeptime="0.037";
    echo -e "\nExecute '$1'";
    sleep $sleeptime;
    #echo "$1" >> commands.bash;
    #sleep $sleeptime;
    #echo "";
    eval "$1";
}

if [ -z "$1" ]
    then
    FROM=$(pwd); FROM="${FROM}/";
    echo "First argument is a \"from\"-directory and it is empty string"
    echo "from-directory set to current dir (${FROM})";
fi

if [ -z "$2" ]
    then
    COPY_TO_SAME_DIR=1;
    TO=$(pwd); TO="${TO}/${COPY_BY_SIZE_DIR}";
    EXCLUDE=" ${EXCLUDE} --exclude=\"${COPY_BY_SIZE_DIR}\" ";
    echo "Second argument is a \"to\"-directory and it is empty string"
    echo "to-directory set to current dir (${TO})";
fi

j=0; #preffix-iterator
MIN_SIZE=0; 
for MAX_SIZE in 0b 1b 10b 100b 300b 1k 10k 30k 100k 300k 1m 3m 10m 30m 100m 300m 1g 3g 10g 30g 100g 300g 1000g 999999g; 
do echo -e "\n\nMIN_SIZE=${MIN_SIZE} MAX_SIZE=${MAX_SIZE}\n\n"; 
    if [ "${COPY_TO_SAME_DIR}" == "1" ];
    then
        j=$((j+1)); 
        PREFFIX=`printf "%02d" $j`; 
        SIZE_DIR="${PREFFIX}--${MIN_SIZE}--${MAX_SIZE}"; 
        TARGET_DIR="${TO}/${SIZE_DIR}"; 
    else
        TARGET_DIR="${TO}";
    fi;

    #echo -e "\n\nMIN_SIZE=${MIN_SIZE} MAX_SIZE=${MAX_SIZE}\n\n";
    mkdir -pv "${TARGET_DIR}"; 
    #sleep 0.1; 
    #rsync --min-size=${MIN_SIZE} --max-size=${MAX_SIZE} --info=progress2 --progress --recursive --times --human-readable --verbose "${EXCLUDE}" "${FROM}/" "${TO}/"; MIN_SIZE=$MAX_SIZE; 
    COMMAND=$(echo "rsync --min-size=${MIN_SIZE} --max-size=${MAX_SIZE} --info=progress2 --progress --recursive --times --human-readable --verbose ${EXCLUDE} \"${FROM}\" \"${TARGET_DIR}\";");
    execute_comm "$COMMAND";
    MIN_SIZE=$MAX_SIZE;
done;
