#!/bin/bash 
#Скрипт генерирует генерирует видео искривления из текста

#INFILE='g.jpg';

INFILE="$1";
#FINAL_RESOLUTION="7680x4320";
FINAL_RESOLUTION="3840x2160";

echo "Create beautiful background";
sleep 0.05;
convert -size 7680x4320 plasma:fractal -swirl 0 -antialias -resize $FINAL_RESOLUTION "text4videofractalbackground.png"; 

echo "Create text with caption \"$INFILE\"";
sleep 0.05;
convert -background transparent -fill black -strokewidth 20 -stroke white -size 7680x4320 -gravity Center caption:"$INFILE" -swirl 0 -antialias  -resize $FINAL_RESOLUTION "imagefromtexttransparent.png"; 

echo "Compose text with the background";
sleep 0.05;
composite -quality 100  "imagefromtexttransparent.png" "text4videofractalbackground.png" "imagefromtext.png"; 

#ffmpeg -nostats -loglevel 0 -y -loop 1 -t 10 -f image2 -i imagefromtext.png -r 30 -vcodec h264 -tune stillimage text4video.mp4; 

echo "Generate blurred background";
sleep 0.05;
#Более размытая версия фона
convert text4videofractalbackground.png -blur 125x125 background-blurred.png

#Генерируем кадры с нарастанием displacement'a
echo "Generate commands";
sleep 0.05;
FRAMESDIR="frames"; 
mkdir -p $FRAMESDIR; 
#Генерируем в цикле команды на создание кадров, сохраняем в файл
#for i in `seq 6500 -1 0`; do printf "%05d\n" $i; composite background-blurred.png imagefromtext.png -displace "$i"x"$i" $FRAMESDIR/"`printf "%05d\n" $i`.png"; done;
echo "" > compose-commands.sh
for i in `seq 2500 -1 0`; 
do printf "%05d\n" $i >/dev/null; 
echo "composite background-blurred.png imagefromtext.png -displace \"$i\"x\"$i\" -quality 95 -resize $FINAL_RESOLUTION $FRAMESDIR/\"`printf \"%05d\n\" $i`.jpg\"; echo -n .;"  >>"compose-commands.sh";
done; 
#Перемешиваем команды в файле
cat "compose-commands.sh" | sort -R > "compose-commands-random.sh"
cp "compose-commands-random.sh" "compose-commands.sh"
echo "Generate frames";
sleep 0.05;
#Выполним команды в несколько потоков
cat "compose-commands.sh" | xargs -I CMD --max-procs=8 bash -c CMD

#ffmpeg -nostats -loglevel 0 -y -loop 1 -t 10 -f image2 -i imagefromtext.png -r 30 -vcodec h264 -tune stillimage text4video.mp4; 

echo "Render video from frames";
sleep 0.05;
ffmpeg -f image2 -i $FRAMESDIR/%05d.jpg -r 60 -vcodec libx264 -preset veryfast -crf 18 video-from-text.mkv

#echo rm --interactive=once --verbose "text4video*"
#rm --verbose "text4videofractalbackground.png"
#rm --interactive=once --verbose text4video*

#seq 15 | xargs --max-procs=4 -n 1 echo
echo "Done.";
sleep 0.35;
