#!/bin/bash
#to run this script use something like this:
#find . -type d -exec md5here '{}' \; | tee md5sum-all-`date "+%F"`.md5 
old_dir=`pwd`;
cd "$1";
echo "";
echo "#`pwd`";
#find . -maxdepth 1 -type f  -exec md5sum --binary {} \; | tee md5here-`date "+%F-%H-%M-%S"`.md5
find . -maxdepth 1 -type f  -exec md5sum --binary {} \; | tee md5-`date "+%F"`.md5
#find . -maxdepth 1 -type f  -exec echo {} \;
#echo "$old_dir $1";
#sleep 0.1;
cd "$old_dir";
