#!/bin/bash 
#Script renames file in current directory. Adds file modify date before file name. Uses exiftool 

for i in *.*; do echo $i; 

# filedate="${i:0:4}-${i:5:2}-${i:8:2} ${i:11:2}:${i:14:2}:${i:17:2}"; 
# datesecs=$(date +%s --date="${filedate}")
# #2019-08-11-14-10-31--482827ms-11
# dateoffsetsecs=${i:21:9}
# #get only digits from variable
# dateoffsetsecs=$(echo ${dateoffsetsecs} | grep -o -E '[0-9]+' | head -1 | sed -e 's/^0\+//')
# echo "dateoffsetsecs = ${dateoffsetsecs}";
# dateoffsetsecs=$((dateoffsetsecs / 1000));
# #dateoffsetsecs=`calc "${dateoffsetsecs} / 1000"`;
# echo "dateoffsetsecs = ${dateoffsetsecs}";
# datesecs=$((datesecs + dateoffsetsecs));
# echo "datesecs = ${datesecs}";
# filedate=$(date '+%F %H:%M:%S' --date="@${datesecs}")
# echo "date = ${filedate}";
# if [ "${datesecs}" -gt "31536000" ]
# then touch -a -m --date="${filedate}" "${i}";
# else echo " -- skipping \"${i}\" cause its too old"; 
# fi; 

done;

exiftool -progress -d %Y-%m-%d_%H-%M-%S-%%-c-%%lf.%%le "-filename<FileModifyDate" *.*
